version: 2.1
orbs:
  docker: circleci/docker@2.1.1
executors:
  # Node environment with Chrome installed for Cypress
  node:
    docker: &node_image
      - image: cypress/browsers:node16.17.0-chrome106
        environment:
          ## this enables colors in the output
          TERM: xterm
          CYPRESS_CACHE_FOLDER: ~/repo/.cypress
    working_directory: ~/repo
    resource_class: medium

jobs:
  build:
    executor: node
    resource_class: medium
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

workflows:
  version: 2

  build:
    jobs:
      - build
