version: 2.1
orbs:
  docker: circleci/docker@2.6.0
  node: circleci/node@7.1.0

executors:
  node:
    docker:
      - image: cimg/node:22.11-browsers
        environment:
          TERM: xterm
          CYPRESS_CACHE_FOLDER: ~/repo/.cypress
    working_directory: ~/repo
    resource_class: medium

jobs:
  build:
    executor: node
    resource_class: medium
    steps:
      - checkout
      - node/install:
          install-pnpm: true
      - run: pnpm install
      - run: pnpm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    executor: node
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-pnpm: true
      - run: pnpm run lint
      - run: pnpm run typecheck

  test:
    executor: node
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-pnpm: true
      - run: pnpm run test

  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-pnpm: true
      - run:
          name: Publish package
          command: pnpm publish --access public

workflows:
  version: 2

  build:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
