version: 2.1
orbs:
  docker: circleci/docker@2.1.1
executors:
  node:
    docker: &node_image
      - image: cimg/node:18.16.1
        environment:
          TERM: xterm
          CYPRESS_CACHE_FOLDER: ~/repo/.cypress
    working_directory: ~/repo
    resource_class: medium

jobs:
  build:
    executor: node
    resource_class: medium
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: "echo \"npmAuthToken: $NPM_TOKEN\" >> ~/repo/.yarnrc.yml"
      - run:
          name: Publish package
          command: yarn npm publish --access public --tolerate-republish

workflows:
  version: 2

  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          # filters:
          #   branches:
          #     only: main
