version: 2.1
orbs:
  docker: circleci/docker@2.1.1

executors:
  node:
    docker: &node_image
      - image: cypress/browsers:node18.12.0-chrome107
        environment:
          ## this enables colors in the output
          TERM: xterm
          CYPRESS_CACHE_FOLDER: ~/repo/.cypress
    working_directory: ~/repo
    resource_class: medium

jobs:
  install:
    executor: node
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules 
      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    executor: node
    resource_class: medium
    steps:
      - run: yarn build
      - attach_workspace:
          at: ~/repo 
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint: 
    executor: node
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/repo 
      - run: yarn lint
    
  test: 
    executor: node
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/repo 
      - run: yarn test
      - run: 
          command: yarn start:test-http-server 
          background: true
      - run: yarn run build:test
      - run: yarn cypress run
      - store_test_results:
          path: /root/repo/cypress/results
      - store_artifacts:
          path: /root/repo/cypress/videos
          destination: cypress-videos
      - store_artifacts:
          path: /root/repo/cypress/screenshots
          destination: cypress-screenshots 

  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: "echo \"npmAuthToken: $NPM_TOKEN\" >> ~/repo/.yarnrc.yml"
      - run:
          name: Publish package
          command: yarn npm publish --access public --tolerate-republish

workflows:
  version: 2

  build:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
      - test: 
          requires:
            - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: main
